---
- name: Setup basic packages
  hosts: test-server
  become: true
  tasks:
   - name: Install packages
     ansible.builtin.package:
      name:
       - htop
       - vim
       - curl
       - wget
       - git
       - tmux
       - zfsutils-linux
       - btm
       - gparted
